import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  patient: defineTable({
    // patientId: v.id("patients"),
    name: v.string(),
    dateOfBirth: v.string(),
    maritalStatus: v.string(),
    identificationNumber: v.string(),
    gender: v.string(),
    homeAddress: v.string(),
    email: v.string(),
    city: v.string(),
    state: v.string(),
    country: v.string(),
    phone: v.number(),
    guardianName: v.string(),
    relationship: v.string(),
    guardianGender: v.string(),
    guardianHomeAddress: v.string(),
    guardianEmail: v.string(),
    guardianCity: v.string(),
    guardianState: v.string(),
    guardianCountry: v.string(),
    guardianPhone: v.number(),
  }),
  doctor: defineTable({
    // doctorId: v.id("doctors"),
    name: v.string(),
    dateOfBirth: v.string(),
    hospital: v.string(),
    specialty: v.string(),
    registrationNumber: v.string(),
    identificationNumber: v.number(),
    yearsOfExperience: v.number(),
    gender: v.string(),
    homeAddress: v.string(),
    email: v.string(),
    status: v.string(),
    city: v.string(),
    state: v.string(),
    country: v.string(),
    phone: v.number(),
  }),
  chats: defineTable({
    author: v.string(),
    body: v.string(),
  }),
});
